version: "3.9"

services:
  backend:
    build: ./backend
    depends_on:
      - postgres
    env_file:
      - env/backend.env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/postgres.env
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
volumes:
  postgres_data: