version: "3.9"

services:
  web:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    env_file:
      - backend/env/web.env
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - backend/env/postgres.env
volumes:
  postgres_data: